<?php

namespace Database\Seeders;

use App\Models\Media;
use Illuminate\Database\Seeder;

class MediaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $brands = [
            [
                'id' => 1,
                'model_type' => "App\Models\Brand",
                'model_id' => 1,
                'uuid' => "fde31522-0333-4312-84b8-c2a9b70c39ba",
                'collection_name' => "image",
                'name' => "62f3cde15e151_logo-asus",
                'file_name' => "62f3cde15e151_logo-asus.png",
                'mime_type' => "image/png",
                'disk' => "public",
                'conversions_disk' => "public",
                'size' => 12315,
                'manipulations' => "[]",
                'custom_properties' => "[]",
                'generated_conversions' => '{"thumb":true,"preview":true}',
                'responsive_images' => "[]",
                'order_column' => 1,
                'created_at' => "2022-08-10 15:25:23",
                'updated_at' => "2022-08-10 15:25:23",        
            ],
            [
                'id' => 2,
                'model_type' => "App\Models\Brand",
                'model_id' => 2,
                'uuid' => "d95f448e-61d9-4d26-bc0a-412921ed363e",
                'collection_name' => "image",
                'name' => "62f3dbb851cc7_logo-hp",
                'file_name' => "62f3dbb851cc7_logo-hp.png",
                'mime_type' => "image/png",
                'disk' => "public",
                'conversions_disk' => "public",
                'size' => 38186,
                'manipulations' => "[]",
                'custom_properties' => "[]",
                'generated_conversions' => '{"thumb":true,"preview":true}',
                'responsive_images' => "[]",
                'order_column' => 2,
                'created_at' => "2022-08-10 15:25:23",
                'updated_at' => "2022-08-10 15:25:23",        
            ],
            [
                'id' => 3,
                'model_type' => "App\Models\Brand",
                'model_id' => 3,
                'uuid' => "ff6e7cad-9b09-4a27-88eb-a53d57e9e11b",
                'collection_name' => "image",
                'name' => "62f3dbc2817b6_logo-lenovo",
                'file_name' => "62f3dbc2817b6_logo-lenovo.png",
                'mime_type' => "image/png",
                'disk' => "public",
                'conversions_disk' => "public",
                'size' => 19314,
                'manipulations' => "[]",
                'custom_properties' => "[]",
                'generated_conversions' => '{"thumb":true,"preview":true}',
                'responsive_images' => "[]",
                'order_column' => 3,
                'created_at' => "2022-08-10 15:25:23",
                'updated_at' => "2022-08-10 15:25:23",        
            ],
            [
                'id' => 4,
                'model_type' => "App\Models\Brand",
                'model_id' => 4,
                'uuid' => "1057a85a-f0be-4b0e-b577-1c3d8191e158",
                'collection_name' => "image",
                'name' => "62f3dbcbada0e_logo-samsung",
                'file_name' => "62f3dbcbada0e_logo-samsung.jpg",
                'mime_type' => "image/jpg",
                'disk' => "public",
                'conversions_disk' => "public",
                'size' => 17735,
                'manipulations' => "[]",
                'custom_properties' => "[]",
                'generated_conversions' => '{"thumb":true,"preview":true}',
                'responsive_images' => "[]",
                'order_column' => 4,
                'created_at' => "2022-08-10 15:25:23",
                'updated_at' => "2022-08-10 15:25:23",        
            ],
            [
                'id' => 5,
                'model_type' => "App\Models\Brand",
                'model_id' => 5,
                'uuid' => "99ed09c6-ba34-451e-8885-8e87769e6aeb",
                'collection_name' => "image",
                'name' => "62f3dbd37fa83_logo-lg",
                'file_name' => "62f3dbd37fa83_logo-lg.jpg",
                'mime_type' => "image/jpg",
                'disk' => "public",
                'conversions_disk' => "public",
                'size' => 71186,
                'manipulations' => "[]",
                'custom_properties' => "[]",
                'generated_conversions' => '{"thumb":true,"preview":true}',
                'responsive_images' => "[]",
                'order_column' => 5,
                'created_at' => "2022-08-10 15:25:23",
                'updated_at' => "2022-08-10 15:25:23",        
            ],
            [
                'id' => 6,
                'model_type' => "App\Models\Brand",
                'model_id' => 6,
                'uuid' => "071cc3f6-0df7-49eb-8a7d-837702c6aba0",
                'collection_name' => "image",
                'name' => "62f3dbdc9248c_logo-fujitsu",
                'file_name' => "62f3dbdc9248c_logo-fujitsu.png",
                'mime_type' => "image/png",
                'disk' => "public",
                'conversions_disk' => "public",
                'size' => 34480,
                'manipulations' => "[]",
                'custom_properties' => "[]",
                'generated_conversions' => '{"thumb":true,"preview":true}',
                'responsive_images' => "[]",
                'order_column' => 6,
                'created_at' => "2022-08-10 15:25:23",
                'updated_at' => "2022-08-10 15:25:23",        
            ],
            [
                'id' => 7,
                'model_type' => "App\Models\Brand",
                'model_id' => 6,
                'uuid' => "dfd018e3-bc03-40d2-a5ba-ed4c5be05997",
                'collection_name' => "image",
                'name' => "62f3dbe6256fb_logo-dell",
                'file_name' => "62f3dbe6256fb_logo-dell.jpg",
                'mime_type' => "image/jpg",
                'disk' => "public",
                'conversions_disk' => "public",
                'size' => 88575,
                'manipulations' => "[]",
                'custom_properties' => "[]",
                'generated_conversions' => '{"thumb":true,"preview":true}',
                'responsive_images' => "[]",
                'order_column' => 6,
                'created_at' => "2022-08-10 15:25:23",
                'updated_at' => "2022-08-10 15:25:23",        
            ],
        ];

        Media::insert($brands);
    }
}
